### ISSUE TITLE
关于 index.d.ts 的一点疑问

### ISSUE THREAD

**Issue by shigma** [jjyyxx/neat-scroll#3]
https://github.com/jjyyxx/neat-scroll/blob/f38e2496d35f5a065b59a7e78607f11add596574/index.d.ts#L27

根据 [MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/scrollTop)，像`scrollTop`这样的属性都是 Element 的属性，不是 HTMLElement 的属性吧？

**Comment by jjyyxx** [comment]
https://github.com/jjyyxx/neat-scroll/blob/9197058800b1638a8093526f3c2ebe68c9f98d2e/index.d.ts#L34
已将target类型调整为一个接口，不强制要求为`Element`，允许传入自定义对象，只要具有对应属性即可。
